In [2]:
import numpy as np

In [3]:
arr = np.arange(0,10)

In [4]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[8]

8

In [6]:
arr[1:3]

array([1, 2])

In [7]:
arr[0:8] = 1 

In [8]:
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 8, 9])

In [9]:
arr = np.arange(0,10)

In [17]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr_part = arr[:6]

In [19]:
arr_part

array([0, 1, 2, 3, 4, 5])

In [20]:
arr_part[:] = 6193

In [21]:
arr_part

array([6193, 6193, 6193, 6193, 6193, 6193])

In [22]:
arr

array([6193, 6193, 6193, 6193, 6193, 6193,    6,    7,    8,    9])

In [23]:
arr_copy = arr.copy()

In [24]:
arr_copy

array([6193, 6193, 6193, 6193, 6193, 6193,    6,    7,    8,    9])

In [25]:
arr_copy[:] = list(range(0,10))

In [26]:
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr

array([6193, 6193, 6193, 6193, 6193, 6193,    6,    7,    8,    9])

In [29]:
arr_2d = np.array(([6,1,9,3],[1,7,3,0],[2,3,1,0]))

In [30]:
arr_2d

array([[6, 1, 9, 3],
       [1, 7, 3, 0],
       [2, 3, 1, 0]])

In [31]:
arr_2d[1][1]

7

In [32]:
arr_2d[1,2]

3

In [33]:
arr_2d[1:3,1:3]

array([[7, 3],
       [3, 1]])

In [34]:
arr_2d[:,2:4]

array([[9, 3],
       [3, 0],
       [1, 0]])

In [36]:
arr_2d1 = np.zeros((5,6)) 

In [37]:
arr_2d1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [41]:
arr_2d1.shape

(5, 6)

In [42]:
arr_2d1.shape[1]

6

In [49]:
own_arr = np.random.randint(5,100,100)

In [51]:
own_arr = own_arr.reshape(10,10)

In [52]:
own_arr

array([[76,  9, 15, 54, 19, 72, 90,  9, 52,  5],
       [58, 86, 89, 76, 10, 78,  5, 20, 64, 56],
       [24, 86, 10, 73, 59, 97, 90, 45, 61, 81],
       [51, 21, 36, 41, 69, 80, 48, 97, 98, 26],
       [66, 49, 75,  9, 69, 47, 16, 16, 68, 39],
       [15, 65, 65, 50, 18, 78, 97, 81, 65, 52],
       [57, 54, 52, 95, 45, 22, 94, 43, 24, 89],
       [42, 51, 24, 10, 63, 33, 86, 32, 17, 83],
       [28, 31, 32, 17, 36, 95, 97, 37, 79, 73],
       [17, 80, 34, 56, 70, 33, 27, 49, 95, 19]])

In [53]:
own_arr[3:6,3:8]

array([[41, 69, 80, 48, 97],
       [ 9, 69, 47, 16, 16],
       [50, 18, 78, 97, 81]])

In [55]:
own_arr[[1,3,6,9]]

array([[58, 86, 89, 76, 10, 78,  5, 20, 64, 56],
       [51, 21, 36, 41, 69, 80, 48, 97, 98, 26],
       [57, 54, 52, 95, 45, 22, 94, 43, 24, 89],
       [17, 80, 34, 56, 70, 33, 27, 49, 95, 19]])

In [56]:
own_arr[[1,2,3,4]]

array([[58, 86, 89, 76, 10, 78,  5, 20, 64, 56],
       [24, 86, 10, 73, 59, 97, 90, 45, 61, 81],
       [51, 21, 36, 41, 69, 80, 48, 97, 98, 26],
       [66, 49, 75,  9, 69, 47, 16, 16, 68, 39]])

In [57]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr2 = arr%2 == 0

In [66]:
arr2

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [67]:
arr[arr2]

array([ 0,  2,  4,  6,  8, 10])

In [68]:
arr[arr%2 == 0]

array([ 0,  2,  4,  6,  8, 10])