In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
matrix = [[1,2,3],[6,1,9],[1,7,3]]

In [5]:
np.array(matrix)

array([[1, 2, 3],
       [6, 1, 9],
       [1, 7, 3]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,6,2)

array([0, 2, 4])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [20]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [22]:
np.random.randn(1,10,3)

array([[[-0.60155502, -0.49126762,  1.22447646],
        [ 1.0338388 ,  0.87851835,  0.05446481],
        [-2.53629528,  0.46540597,  1.34408188],
        [-0.70381039, -0.872492  , -0.85483463],
        [ 0.6463209 , -0.36703566, -0.76083584],
        [-0.03911915, -0.08361995,  2.54834083],
        [ 0.86553187, -0.415494  , -2.29366721],
        [ 1.39048358, -1.81990085,  2.90298963],
        [-1.47317512,  2.80767659, -1.1276785 ],
        [ 2.17620461,  0.54476463, -0.73789369]]])

In [23]:
np.random.randn(2)

array([0.3803597 , 0.06125571])

In [24]:
np.random.randn(1,3)

array([[ 1.96472818,  0.86598699, -0.29361734]])

In [25]:
np.random.randn(5,5)

array([[ 0.4205689 , -0.57975248,  0.27128732,  0.0227808 ,  0.22206365],
       [ 1.49375181, -1.32761652,  0.0932182 ,  0.69831621, -0.84020471],
       [-0.4618041 , -0.7081637 ,  0.75116917, -0.74206619,  0.59902263],
       [ 0.18975456,  0.43381872, -0.03998116,  1.03978632,  0.81919589],
       [-1.14364736,  0.57195926,  1.17895199, -0.61632747, -0.4103691 ]])

In [26]:
np.random.rand(2)

array([0.07932712, 0.61737068])

In [27]:
np.random.rand(5,5)

array([[0.81974423, 0.77702753, 0.00128881, 0.15901073, 0.11251154],
       [0.13206752, 0.50425336, 0.82854725, 0.53681443, 0.48766045],
       [0.65710697, 0.108045  , 0.93430366, 0.99217137, 0.44274252],
       [0.81995586, 0.35878094, 0.74767039, 0.36839962, 0.26501095],
       [0.69971515, 0.66958107, 0.79848453, 0.13060418, 0.77394651]])

In [46]:
np.random.randint(3,4)

3

In [48]:
np.random.randint(3,4,2)

array([3, 3])

In [49]:
from random import randint

In [56]:
ran = randint(2,4)

In [57]:
ran

3

In [59]:
arr = np.arange(0,10)

In [60]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
ranarr = np.random.randint(0,15,10)

In [62]:
ranarr

array([ 0,  3, 14,  8, 14,  9, 11,  9, 12, 13])

In [68]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 10 into shape (2,6)

In [70]:
ranarr

array([ 0,  3, 14,  8, 14,  9, 11,  9, 12, 13])

In [71]:
ranarr.max

<function ndarray.max>

In [72]:
ranarr.max()

14

In [73]:
ranarr.argmax()

2

In [74]:
ranarr.min()

0

In [75]:
ranarr.argmin()

0

In [76]:
ranarr.shape

(10,)

In [79]:
ranarr.reshape(5,2).shape

(5, 2)

In [81]:
ranarr.reshape(1,10)

array([[ 0,  3, 14,  8, 14,  9, 11,  9, 12, 13]])

In [83]:
ranarr

array([ 0,  3, 14,  8, 14,  9, 11,  9, 12, 13])

In [84]:
ranarr.reshape(10,1)

array([[ 0],
       [ 3],
       [14],
       [ 8],
       [14],
       [ 9],
       [11],
       [ 9],
       [12],
       [13]])

In [85]:
ranarr.reshape(10,1).shape

(10, 1)

In [87]:
ranarr.dtype

dtype('int32')

In [88]:
arr.dtype

dtype('int32')